local _ = ... -- Internal namespace
local LSM = LibStub("LibSharedMedia-3.0")
MentionedMedia = {}
LSM:Register("font","Expressway", [[Interface\Addons\NorthernSkyRaidTools\Media\Fonts\Expressway.TTF]])
--StatusBars
LSM:Register("statusbar","Atrocity", [[Interface\Addons\NorthernSkyRaidTools\Media\StatusBars\Atrocity]])


MentionedMedia.BreakMemes = {
        {[[Interface\AddOns\MentionedUtils\Memes\daitosus.png]], 384, 366},
        {[[Interface\AddOns\MentionedUtils\Memes\draganehello.png]], 384, 405},
        {[[Interface\AddOns\MentionedUtils\Memes\draganemarkus.png]], 384, 405},
        {[[Interface\AddOns\MentionedUtils\Memes\draganepoop.png]], 384, 405},
        {[[Interface\AddOns\MentionedUtils\Memes\draganetish.png]], 384, 405},
        {[[Interface\AddOns\MentionedUtils\Memes\draganewtf.png]], 384, 405},
        {[[Interface\AddOns\MentionedUtils\Memes\eggwa.png]], 384, 534},
        {[[Interface\AddOns\MentionedUtils\Memes\fknlatoss.png]], 384, 682},
        {[[Interface\AddOns\MentionedUtils\Memes\guffyass.png]], 384, 514},
        {[[Interface\AddOns\MentionedUtils\Memes\kylgequest.png]], 384, 249},
        {[[Interface\AddOns\MentionedUtils\Memes\whoraclemicdown.png]], 384, 249},
        {[[Interface\AddOns\MentionedUtils\Memes\gaffymage.png]], 384, 486},
        {[[Interface\AddOns\MentionedUtils\Memes\postburgersadness.jpg]], 384, 682},
        {[[Interface\AddOns\MentionedUtils\Memes\draganesleep.png]], 384, 343},
        {[[Interface\AddOns\MentionedUtils\Memes\antdate.jpg]], 384, 514},
        {[[Interface\AddOns\MentionedUtils\Memes\antmirror.jpg]], 384, 512},
        {[[Interface\AddOns\MentionedUtils\Memes\draganebaby.jpg]], 384, 512},
        {[[Interface\AddOns\MentionedUtils\Memes\draganeburger.png]], 384, 479},
        {[[Interface\AddOns\MentionedUtils\Memes\draganeglasses.jpg]], 384, 682},
        {[[Interface\AddOns\MentionedUtils\Memes\draganekid.png]], 384, 519},
        {[[Interface\AddOns\MentionedUtils\Memes\draganemirror.jpg]], 384, 682},
        {[[Interface\AddOns\MentionedUtils\Memes\draganerave.png]], 384, 831},
        {[[Interface\AddOns\MentionedUtils\Memes\weecepiano.png]], 384, 362},
        {[[Interface\AddOns\MentionedUtils\Memes\daitotoilet.png]], 384, 384},
        {[[Interface\AddOns\MentionedUtils\Memes\tishcat.png]], 384, 515},
        {[[Interface\AddOns\MentionedUtils\Memes\antdrunk.png]], 384, 513},
        {[[Interface\AddOns\MentionedUtils\Memes\tishcamp.png]], 384, 384},
        {[[Interface\AddOns\MentionedUtils\Memes\daitoski.jpg]], 384, 512},
        {[[Interface\AddOns\MentionedUtils\Memes\daitoclose.png]], 384, 437},
        {[[Interface\AddOns\MentionedUtils\Memes\antclose.png]], 384, 409},
        {[[Interface\AddOns\MentionedUtils\Memes\ant.jpg]], 384, 682},
        {[[Interface\AddOns\MentionedUtils\Memes\cinema.png]], 384, 208},
        {[[Interface\AddOns\MentionedUtils\Memes\consagrin.png]], 384, 344},
        {[[Interface\AddOns\MentionedUtils\Memes\tishpaying.png]], 384, 256},
        {[[Interface\AddOns\MentionedUtils\Memes\chineseoverlord.png]], 384, 420},
        {[[Interface\AddOns\MentionedUtils\Memes\daitoo.png]], 384, 413},
        {[[Interface\AddOns\MentionedUtils\Memes\daitossj4.png]], 384, 301},
        {[[Interface\AddOns\MentionedUtils\Memes\daitowipe.png]], 384, 317},
        {[[Interface\AddOns\MentionedUtils\Memes\draganehands.png]], 384, 442},
        {[[Interface\AddOns\MentionedUtils\Memes\draganerage.png]], 384, 376},
        {[[Interface\AddOns\MentionedUtils\Memes\dragglad.png]], 384, 354},
        {[[Interface\AddOns\MentionedUtils\Memes\dragshock.png]], 384, 191},
        {[[Interface\AddOns\MentionedUtils\Memes\dragsweat.png]], 384, 407},
        {[[Interface\AddOns\MentionedUtils\Memes\fibbo.png]], 384, 384},
        {[[Interface\AddOns\MentionedUtils\Memes\kazmilded.png]], 384, 426},
        {[[Interface\AddOns\MentionedUtils\Memes\serbiansquirrel.png]], 384, 406},
        {[[Interface\AddOns\MentionedUtils\Memes\tisheatcat.png]], 384, 503},
        {[[Interface\AddOns\MentionedUtils\Memes\tishippie.png]], 384, 473},
        {[[Interface\AddOns\MentionedUtils\Memes\weeceshock.png]], 384, 343},
        }